### ISSUE TITLE
Allow unTab window to open in a new empty tab

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#51] opened 2021-03-10 15:30 UTC
The unTab window opens only in those tabs which aren't empty. If we open a new tab and try to open unTab window by pressing ```ctrl```+```shift```+```space``` then it does not open. It would be really helpful if we could open unTab window even in empty tabs.

**Comment by blenderskool** [comment] 2021-03-10 15:37
Closing as a duplicate of #48

**Closed by blenderskool** 2021-03-10 15:37 UTC
